services:
  - type: web
    name: diabetic-predictor
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
